version: "3.8"

services:
  database:
    container_name: ${CONTAINER_BASENAME}_database
    image: mariadb:jammy
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  php:
    container_name: ${CONTAINER_BASENAME}_php
    image: ${IMAGE}
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - chevereto:/var/www/html/
      - type: bind
        source: ${SOURCE}
        target: /var/www/chevereto
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    restart: always
    environment:
      CHEVERETO_ENVIRONMENT: dev
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HOSTNAME: ${HOSTNAME}
      CHEVERETO_HOSTNAME_PATH: ${HOSTNAME_PATH}
      CHEVERETO_HTTPS: ${HTTPS}
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: ${URL}images/_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/images/_assets/
      CHEVERETO_ENCRYPTION_KEY: ${ENCRYPTION_KEY}

volumes:
  database:
  assets:
  storage:
  chevereto:

networks:
  chevereto:
